name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - uses: astral-sh/setup-uv@v3
      - run: uv sync --dev
      - name: Lint code
        run: uv run ruff check
      - name: Check formatting
        run: uv run ruff format --check

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - uses: astral-sh/setup-uv@v3
      - run: uv sync --dev --extra=apps
      - name: Check types
        run: uv run mypy .

  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    strategy:
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v3
      - run: uv sync --dev --extra=apps
      - name: Run pytest
        run: uv run pytest --junitxml=pytest.xml --cov=faststack --cov-report=xml:coverage.xml
      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
          unique-id-for-comment: ${{ matrix.python-version }}
          title: Coverage (${{ matrix.python-version }})
          badge-title: Coverage (${{ matrix.python-version }})
